# Generated by Django 3.2.6 on 2021-08-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField()),
                ('open_time', models.CharField(max_length=255)),
                ('type_st', models.CharField(max_length=255)),
                ('size_st', models.FloatField()),
                ('item_st', models.CharField(max_length=255)),
                ('open_price', models.FloatField()),
                ('s_l', models.FloatField(blank=True, null=True)),
                ('t_p', models.FloatField(blank=True, null=True)),
                ('close_time', models.CharField(max_length=255)),
                ('close_price', models.FloatField()),
                ('commission', models.FloatField()),
                ('taxes', models.IntegerField(blank=True, null=True)),
                ('swap', models.IntegerField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
