# Generated by Django 3.2.7 on 2023-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0027_auto_20210913_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_depo', models.IntegerField(blank=True, null=True)),
                ('point_real', models.IntegerField(blank=True, null=True)),
                ('point_virtual', models.IntegerField(blank=True, null=True)),
                ('percent_real', models.FloatField(blank=True, null=True)),
                ('percent_virtual', models.FloatField(blank=True, null=True)),
                ('depo_year', models.IntegerField(blank=True, null=True)),
                ('percent_year', models.FloatField(blank=True, null=True)),
                ('years_year', models.IntegerField(blank=True, null=True)),
                ('months_year', models.IntegerField(blank=True, null=True)),
                ('days_year', models.IntegerField(blank=True, null=True)),
                ('depo_month', models.IntegerField(blank=True, null=True)),
                ('percent_month', models.FloatField(blank=True, null=True)),
                ('wd_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buy_calc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notesdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pipmargin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
