# Generated by Django 3.2.7 on 2023-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0028_auto_20230219_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='profit_month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
