# Generated by Django 3.2.7 on 2023-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0029_strategy_profit_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='profit_month',
        ),
        migrations.AddField(
            model_name='strategy',
            name='depo_month_cp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='profit_month_cp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='wd_month_cp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
