# Generated by Django 3.2.7 on 2023-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0030_auto_20230319_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='profit_month_cp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
