# Generated by Django 2.2.10 on 2021-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='open_time',
            field=models.DateTimeField(),
        ),
    ]
