# Generated by Django 3.2.6 on 2021-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0011_notesdb_buy_or_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesdb',
            name='Buy_or_sell',
        ),
        migrations.AddField(
            model_name='notesdb',
            name='buy_or_sell',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
