# Generated by Django 3.2.7 on 2021-09-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0024_pipmargin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipmargin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
