# Generated by Django 3.2.6 on 2021-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0006_auto_20210827_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_wd', models.DateTimeField()),
                ('amount_wd', models.FloatField()),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
    ]
