# Generated by Django 3.2.6 on 2021-09-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0014_alter_notesdb_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesdb',
            name='buy_or_sell',
            field=models.CharField(max_length=255),
        ),
    ]
