# Generated by Django 3.2.6 on 2021-09-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0020_auto_20210902_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter',
            old_name='date_dep',
            new_name='date',
        ),
    ]
