# Generated by Django 3.2.6 on 2021-09-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0019_auto_20210902_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dep', models.DateTimeField()),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='notesdb',
            name='amount_quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesdb',
            name='percent_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesdb',
            name='percent_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesdb',
            name='percent_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
