# Generated by Django 3.2.6 on 2021-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0003_alter_statement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dep', models.DateTimeField()),
                ('amount_dep', models.FloatField()),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
    ]
