# Generated by Django 3.2.6 on 2021-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0010_auto_20210831_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdb',
            name='Buy_or_sell',
            field=models.BooleanField(blank=True, choices=[(True, 'Buy'), (False, 'Sell')], null=True),
        ),
    ]
