# Generated by Django 3.2.6 on 2021-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0013_alter_notesdb_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesdb',
            name='buy_or_sell',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
