# Generated by Django 2.2.10 on 2021-09-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0016_auto_20210902_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesdb',
            old_name='tp_buy',
            new_name='tp',
        ),
        migrations.RemoveField(
            model_name='notesdb',
            name='tp_sell',
        ),
    ]
