# Generated by Django 2.2.10 on 2021-09-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0017_auto_20210902_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell_calc',
        ),
    ]
