# Generated by Django 3.2.7 on 2021-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0025_pipmargin_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdb',
            name='daily_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notesdb',
            name='lot_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
